### ISSUE TITLE
Stamen Tile no longer Free, Sandbox missing basemaps. 

### ISSUE THREAD

**Issue by mapninja** [joeyklee/geosandbox#1]
Suggest replacing Stamen Tile service URLs with something like:

https://tile.openstreetmap.org/{z}/{x}/{y}.png

**Comment by joeyklee** [comment]
Hi @mapninja ! Wow! Thanks for flagging this. I will try to get to this soon. Definitely appreciate your note (I haven't updated the site in ages!) ❤️

**Comment by mapninja** [comment]
> Hi @mapninja ! Wow! Thanks for flagging this. I will try to get to this soon. Definitely appreciate your note (I haven't updated the site in ages!) ❤️

I still use this site to teach web mapping to my "Fundamentals of GISci" Class! My students love it!

**Comment by joeyklee** [comment]
Oh yay! That's wonderful to hear! 

Somewhat related: do you have a preference for teaching with `const/let` for variable declarations? This was written _a while ago_ so it's using `var` but would be happy to update to more modern syntax 🙈

**Comment by joeyklee** [comment]
Okie doke this should be fixed now in https://github.com/joeyklee/geosandbox/commit/481063751821de9ef8cfbc5cedcc3db686a5c8fd 🖖 !

**Comment by joeyklee** [comment]
Thanks again for reporting! ✨
